package main

const (
	gb = 1024 * 1024 * 1024
	mb = 1024 * 1024
)

func defaultAgentConfig() AgentConfig {
	t := templates()[0]
	return AgentConfig{
		Name:                     "Virtual VPS",
		Enabled:                  false,
		ReportIntervalSeconds:    10,
		BasicInfoIntervalMinutes: 5,
		ReconnectIntervalSeconds: 5,
		BasicInfo:                t.BasicInfo,
		Behavior:                 t.Behavior,
	}
}

func templates() []Template {
	return []Template{
		{
			ID:   "linux-vps",
			Name: "Linux VPS",
			BasicInfo: BasicInfo{
				Arch:             "amd64",
				CPUCores:         2,
				CPUPhysicalCores: 1,
				CPUName:          "Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz",
				DiskTotal:        40 * gb,
				GPUName:          "",
				IPv4:             "203.0.113.10",
				IPv6:             "",
				MemTotal:         2 * gb,
				OS:               "Ubuntu 24.04 LTS",
				KernelVersion:    "6.8.0-63-generic",
				SwapTotal:        1 * gb,
				Version:          "fake-komari-agent/" + appVersion,
				Virtualization:   "KVM",
			},
			Behavior: AgentBehavior{
				CPU:                       FloatMetric{Base: 12, Jitter: 6, Min: 0, Max: 100},
				RAMUsedPercent:            FloatMetric{Base: 42, Jitter: 8, Min: 0, Max: 100},
				SwapUsedPercent:           FloatMetric{Base: 4, Jitter: 2, Min: 0, Max: 100},
				DiskUsedPercent:           FloatMetric{Base: 35, Jitter: 1, Min: 0, Max: 100},
				NetworkUpBytesPerSecond:   FloatMetric{Base: 64 * 1024, Jitter: 48 * 1024, Min: 0, Max: 5 * mb},
				NetworkDownBytesPerSecond: FloatMetric{Base: 160 * 1024, Jitter: 96 * 1024, Min: 0, Max: 10 * mb},
				Load1:                     FloatMetric{Base: 0.15, Jitter: 0.08, Min: 0, Max: 1000},
				Load5:                     FloatMetric{Base: 0.12, Jitter: 0.05, Min: 0, Max: 1000},
				Load15:                    FloatMetric{Base: 0.10, Jitter: 0.04, Min: 0, Max: 1000},
				TCPConnections:            IntMetric{Base: 32, Jitter: 12, Min: 0, Max: 2000},
				UDPConnections:            IntMetric{Base: 4, Jitter: 2, Min: 0, Max: 2000},
				Processes:                 IntMetric{Base: 96, Jitter: 16, Min: 1, Max: 10000},
				InitialTotalUp:            12 * gb,
				InitialTotalDown:          28 * gb,
				InitialUptimeSeconds:      7 * 24 * 3600,
				Message:                   "",
			},
		},
		{
			ID:   "debian-lxc",
			Name: "Debian LXC",
			BasicInfo: BasicInfo{
				Arch:             "amd64",
				CPUCores:         1,
				CPUPhysicalCores: 0,
				CPUName:          "AMD EPYC 7B13",
				DiskTotal:        20 * gb,
				GPUName:          "",
				IPv4:             "198.51.100.24",
				IPv6:             "",
				MemTotal:         1 * gb,
				OS:               "Debian GNU/Linux 12",
				KernelVersion:    "6.1.0-37-amd64",
				SwapTotal:        512 * mb,
				Version:          "fake-komari-agent/" + appVersion,
				Virtualization:   "LXC",
			},
			Behavior: AgentBehavior{
				CPU:                       FloatMetric{Base: 8, Jitter: 5, Min: 0, Max: 100},
				RAMUsedPercent:            FloatMetric{Base: 55, Jitter: 10, Min: 0, Max: 100},
				SwapUsedPercent:           FloatMetric{Base: 8, Jitter: 3, Min: 0, Max: 100},
				DiskUsedPercent:           FloatMetric{Base: 47, Jitter: 1, Min: 0, Max: 100},
				NetworkUpBytesPerSecond:   FloatMetric{Base: 32 * 1024, Jitter: 20 * 1024, Min: 0, Max: 3 * mb},
				NetworkDownBytesPerSecond: FloatMetric{Base: 96 * 1024, Jitter: 80 * 1024, Min: 0, Max: 6 * mb},
				Load1:                     FloatMetric{Base: 0.08, Jitter: 0.04, Min: 0, Max: 1000},
				Load5:                     FloatMetric{Base: 0.07, Jitter: 0.03, Min: 0, Max: 1000},
				Load15:                    FloatMetric{Base: 0.06, Jitter: 0.02, Min: 0, Max: 1000},
				TCPConnections:            IntMetric{Base: 18, Jitter: 8, Min: 0, Max: 2000},
				UDPConnections:            IntMetric{Base: 2, Jitter: 1, Min: 0, Max: 2000},
				Processes:                 IntMetric{Base: 58, Jitter: 10, Min: 1, Max: 10000},
				InitialTotalUp:            4 * gb,
				InitialTotalDown:          11 * gb,
				InitialUptimeSeconds:      3 * 24 * 3600,
				Message:                   "",
			},
		},
		{
			ID:   "windows",
			Name: "Windows Desktop",
			BasicInfo: BasicInfo{
				Arch:             "amd64",
				CPUCores:         8,
				CPUPhysicalCores: 4,
				CPUName:          "Intel(R) Core(TM) i7-12700H",
				DiskTotal:        512 * gb,
				GPUName:          "NVIDIA GeForce RTX 4060 Laptop GPU",
				IPv4:             "192.0.2.50",
				IPv6:             "",
				MemTotal:         16 * gb,
				OS:               "Windows 11 Pro",
				KernelVersion:    "26100.4652",
				SwapTotal:        8 * gb,
				Version:          "fake-komari-agent/" + appVersion,
				Virtualization:   "None",
			},
			Behavior: AgentBehavior{
				CPU:                       FloatMetric{Base: 18, Jitter: 12, Min: 0, Max: 100},
				RAMUsedPercent:            FloatMetric{Base: 61, Jitter: 9, Min: 0, Max: 100},
				SwapUsedPercent:           FloatMetric{Base: 12, Jitter: 4, Min: 0, Max: 100},
				DiskUsedPercent:           FloatMetric{Base: 68, Jitter: 1, Min: 0, Max: 100},
				NetworkUpBytesPerSecond:   FloatMetric{Base: 96 * 1024, Jitter: 64 * 1024, Min: 0, Max: 8 * mb},
				NetworkDownBytesPerSecond: FloatMetric{Base: 320 * 1024, Jitter: 180 * 1024, Min: 0, Max: 20 * mb},
				Load1:                     FloatMetric{Base: 0.50, Jitter: 0.25, Min: 0, Max: 1000},
				Load5:                     FloatMetric{Base: 0.40, Jitter: 0.18, Min: 0, Max: 1000},
				Load15:                    FloatMetric{Base: 0.35, Jitter: 0.14, Min: 0, Max: 1000},
				TCPConnections:            IntMetric{Base: 120, Jitter: 35, Min: 0, Max: 5000},
				UDPConnections:            IntMetric{Base: 16, Jitter: 5, Min: 0, Max: 5000},
				Processes:                 IntMetric{Base: 210, Jitter: 24, Min: 1, Max: 10000},
				InitialTotalUp:            80 * gb,
				InitialTotalDown:          190 * gb,
				InitialUptimeSeconds:      12 * 3600,
				Message:                   "",
			},
		},
		{
			ID:   "arm-nas",
			Name: "ARM NAS",
			BasicInfo: BasicInfo{
				Arch:             "arm64",
				CPUCores:         4,
				CPUPhysicalCores: 4,
				CPUName:          "ARM Cortex-A55",
				DiskTotal:        2 * 1024 * gb,
				GPUName:          "",
				IPv4:             "10.0.0.20",
				IPv6:             "",
				MemTotal:         4 * gb,
				OS:               "Debian GNU/Linux 12",
				KernelVersion:    "6.6.31",
				SwapTotal:        2 * gb,
				Version:          "fake-komari-agent/" + appVersion,
				Virtualization:   "None",
			},
			Behavior: AgentBehavior{
				CPU:                       FloatMetric{Base: 22, Jitter: 10, Min: 0, Max: 100},
				RAMUsedPercent:            FloatMetric{Base: 48, Jitter: 6, Min: 0, Max: 100},
				SwapUsedPercent:           FloatMetric{Base: 2, Jitter: 1, Min: 0, Max: 100},
				DiskUsedPercent:           FloatMetric{Base: 72, Jitter: 0.5, Min: 0, Max: 100},
				NetworkUpBytesPerSecond:   FloatMetric{Base: 220 * 1024, Jitter: 120 * 1024, Min: 0, Max: 30 * mb},
				NetworkDownBytesPerSecond: FloatMetric{Base: 180 * 1024, Jitter: 90 * 1024, Min: 0, Max: 30 * mb},
				Load1:                     FloatMetric{Base: 0.85, Jitter: 0.25, Min: 0, Max: 1000},
				Load5:                     FloatMetric{Base: 0.70, Jitter: 0.18, Min: 0, Max: 1000},
				Load15:                    FloatMetric{Base: 0.55, Jitter: 0.12, Min: 0, Max: 1000},
				TCPConnections:            IntMetric{Base: 70, Jitter: 20, Min: 0, Max: 3000},
				UDPConnections:            IntMetric{Base: 6, Jitter: 2, Min: 0, Max: 3000},
				Processes:                 IntMetric{Base: 135, Jitter: 15, Min: 1, Max: 10000},
				InitialTotalUp:            260 * gb,
				InitialTotalDown:          430 * gb,
				InitialUptimeSeconds:      30 * 24 * 3600,
				Message:                   "",
			},
		},
	}
}
